(function(){
var lightShots=['01-howl__mode-light__theme-parchment__bubble-editorial.jpg','02-bird-debate__mode-light__theme-cobaltFrost__bubble-character.jpg','03-car-ride__mode-light__theme-graphite__bubble-editorial.jpg','04-sunbeam__mode-light__theme-signalAmber__bubble-editorial.jpg','05-yard-patrol__mode-light__theme-sonarLime__bubble-character.jpg','06-ball-obsession__mode-light__theme-ultraviolet__bubble-comic.jpg','07-door-alert__mode-light__theme-signalAmber__bubble-character.jpg','08-dinner-demand__mode-light__theme-roseQuartz__bubble-character.jpg','09-nap__mode-light__theme-parchment__bubble-editorial.jpg','10-squirrel-bush__mode-light__theme-sonarLime__bubble-character.jpg','11-sock-incident__mode-light__theme-roseQuartz__bubble-comic.jpg','12-two-dog-guard__mode-light__theme-graphite__bubble-character.jpg'];
var darkShots=['01-howl__mode-dark__theme-cobaltFrost__bubble-editorial.jpg','02-bird-debate__mode-dark__theme-abyssTeal__bubble-character.jpg','03-car-ride__mode-dark__theme-cobaltFrost__bubble-editorial.jpg','04-sunbeam__mode-dark__theme-signalAmber__bubble-editorial.jpg','05-yard-patrol__mode-dark__theme-abyssTeal__bubble-character.jpg','06-ball-obsession__mode-dark__theme-ultraviolet__bubble-comic.jpg','07-door-alert__mode-dark__theme-signalAmber__bubble-character.jpg','08-dinner-demand__mode-dark__theme-roseQuartz__bubble-character.jpg','09-nap__mode-dark__theme-graphite__bubble-editorial.jpg','10-squirrel-bush__mode-dark__theme-sonarLime__bubble-character.jpg','11-sock-incident__mode-dark__theme-ultraviolet__bubble-comic.jpg','12-two-dog-guard__mode-dark__theme-abyssTeal__bubble-character.jpg'];
var image=document.querySelector('[data-carousel-image]'),dots=document.querySelector('[data-carousel-dots]'),deck=document.querySelector('[data-card-deck]');if(!image||!dots||!deck)return;
var count=document.getElementById('darkCount')||document.getElementById('beigeCount');var shots=document.getElementById('darkCount')?darkShots:lightShots;
var n=0,paused=true,timer,animating=false,wheelLock=false,dragging=false,dragStart=0,dragDelta=0;var sideCards=Array.prototype.slice.call(document.querySelectorAll('[data-deck-card]'));
shots.forEach(function(_,i){var b=document.createElement('button');b.setAttribute('aria-label','Show screenshot '+(i+1));b.onclick=function(){go(i,i>=n?1:-1);start()};dots.appendChild(b)});
function render(){image.src='img/shots/web/'+shots[n];sideCards.forEach(function(card){var offset=parseInt(card.getAttribute('data-deck-card'),10);card.src='img/shots/web/'+shots[(n+offset+shots.length)%shots.length]});Array.prototype.forEach.call(dots.children,function(d,j){d.classList.toggle('active',j===n)});if(count)count.textContent=String(n+1).padStart(2,'0')+' / '+shots.length}
function go(i,direction){if(animating)return;animating=true;var dir=direction<0?'prev':'next';deck.classList.add('slide-out-'+dir);setTimeout(function(){n=(i+shots.length)%shots.length;render();deck.classList.remove('slide-out-'+dir);deck.classList.add('slide-in-'+dir);requestAnimationFrame(function(){requestAnimationFrame(function(){deck.classList.remove('slide-in-'+dir)})});setTimeout(function(){animating=false},300)},220)}
function start(){clearInterval(timer)}
document.querySelector('[data-carousel-prev]').onclick=function(){go(n-1,-1)};document.querySelector('[data-carousel-next]').onclick=function(){go(n+1,1)};var autoToggle=document.querySelector('[data-carousel-toggle]');if(autoToggle)autoToggle.hidden=true;
deck.addEventListener('wheel',function(e){var amount=e.shiftKey&&Math.abs(e.deltaY)>Math.abs(e.deltaX)?e.deltaY:e.deltaX;if(!e.shiftKey&&(Math.abs(e.deltaX)<=Math.abs(e.deltaY)||Math.abs(e.deltaX)<8))return;if(Math.abs(amount)<8)return;e.preventDefault();if(wheelLock||animating)return;wheelLock=true;go(n+(amount>0?1:-1),amount>0?1:-1);start();setTimeout(function(){wheelLock=false},520)},{passive:false});
deck.addEventListener('pointerdown',function(e){dragging=true;dragStart=e.clientX;dragDelta=0;deck.setPointerCapture(e.pointerId);deck.classList.add('is-dragging')});deck.addEventListener('pointermove',function(e){if(!dragging)return;dragDelta=e.clientX-dragStart;deck.style.setProperty('--drag-x',dragDelta+'px')});function endDrag(){if(!dragging)return;dragging=false;deck.classList.remove('is-dragging');deck.style.removeProperty('--drag-x');if(Math.abs(dragDelta)>55){go(n+(dragDelta<0?1:-1),dragDelta<0?1:-1);start()}}deck.addEventListener('pointerup',endDrag);deck.addEventListener('pointercancel',endDrag);
var tilt=document.querySelector('[data-tilt-card]');if(tilt){tilt.addEventListener('pointermove',function(e){if(dragging)return;var r=tilt.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tilt.style.setProperty('--rx',(-y*13).toFixed(2)+'deg');tilt.style.setProperty('--ry',(x*15).toFixed(2)+'deg');tilt.style.setProperty('--gx',(x*100+50).toFixed(1)+'%');tilt.style.setProperty('--gy',(y*100+50).toFixed(1)+'%')});tilt.addEventListener('pointerleave',function(){tilt.style.setProperty('--rx','0deg');tilt.style.setProperty('--ry','0deg')})}
document.querySelectorAll('.fft-bars').forEach(function(wave){for(var i=0;i<72;i++){var bar=document.createElement('i');var envelope=Math.sin(i/71*Math.PI),texture=.42+.58*Math.abs(Math.sin(i*.91)+Math.cos(i*.37))/2;bar.style.height=(8+envelope*texture*76)+'%';bar.style.setProperty('--i',i);wave.appendChild(bar)}});var oldWave=document.querySelector('.deck-wave svg');if(oldWave){var replacement=document.createElement('div');replacement.className='fft-bars';oldWave.replaceWith(replacement);for(var j=0;j<72;j++){var rb=document.createElement('i');var env=Math.sin(j/71*Math.PI),tex=.42+.58*Math.abs(Math.sin(j*.91)+Math.cos(j*.37))/2;rb.style.height=(8+env*tex*76)+'%';rb.style.setProperty('--i',j);replacement.appendChild(rb)}}render();start();
})();
